In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\rsang\Downloads\anime.csv")

In [2]:
print(df.shape)
print(df.head)

(12294, 7)
<bound method NDFrame.head of        anime_id                                               name  \
0         32281                                     Kimi no Na wa.
1          5114                   Fullmetal Alchemist: Brotherhood
2         28977                                           Gintama°
3          9253                                        Steins;Gate
4          9969                                      Gintama&#039;
...         ...                                                ...
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami
12290      5543                                        Under World
12291      5621                     Violence Gekiga David no Hoshi
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...
12293     26081                   Yasuji no Pornorama: Yacchimae!!

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51
3                                       Sci-Fi, Thriller     TV       24
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51
...                                                  ...    ...      ...
12289                                             Hentai    OVA        1
12290                                             Hentai    OVA        1
12291                                             Hentai    OVA        4
12292                                             Hentai    OVA        1
12293                                             Hentai  Movie        1

       rating  members
0        9.37   200630
1        9.26   793665
2        9.25   114262
3        9.17   673572
4        9.16   151266
...       ...      ...
12289    4.15      211
12290    4.28      183
12291    4.88      219
12292    4.98      175
12293    5.46      142

[12294 rows x 7 columns]>

In [17]:
print(df.head())

   anime_id                              name  \
0     32281                    Kimi no Na wa.
1      5114  Fullmetal Alchemist: Brotherhood
2     28977                          Gintama°
3      9253                       Steins;Gate
4      9969                     Gintama&#039;

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25
3                                   Sci-Fi, Thriller     TV       24    9.17
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16

   members
0   200630
1   793665
2   114262
3   673572
4   151266

In [9]:
print(df.iloc[0,0])

32281

In [6]:
df.loc[0,"name"]

'Kimi no Na wa.'

In [8]:
print(df.iloc[0,5])

9.37

In [10]:
df.iloc[0:3, 0:3]

,anime_id,name,genre
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural"
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili..."
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S..."

In [14]:
df.iloc[0:5, [1,5]]

                               name  rating
0                    Kimi no Na wa.    9.37
1  Fullmetal Alchemist: Brotherhood    9.26
2                          Gintama°    9.25
3                       Steins;Gate    9.17
4                     Gintama&#039;    9.16

In [13]:
df.loc[0:4, ["name","rating"]]

                               name  rating
0                    Kimi no Na wa.    9.37
1  Fullmetal Alchemist: Brotherhood    9.26
2                          Gintama°    9.25
3                       Steins;Gate    9.17
4                     Gintama&#039;    9.16

In [16]:
df.columns.tolist()
# ['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members']
#       0         1       2       3          4           5          6

['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members']

In [19]:
for i, col in enumerate(df.columns):
    print(i, col)

0 anime_id
1 name
2 genre
3 type
4 episodes
5 rating
6 members

In [20]:
df.iloc[0:5, [1,5]]

                               name  rating
0                    Kimi no Na wa.    9.37
1  Fullmetal Alchemist: Brotherhood    9.26
2                          Gintama°    9.25
3                       Steins;Gate    9.17
4                     Gintama&#039;    9.16

In [23]:
df["rating"].apply(lambda x: x +1)
df["rating"].apply(lambda x: "Good" if x >= 7 else "Bad")

0        Good
1        Good
2        Good
3        Good
4        Good
         ...
12289     Bad
12290     Bad
12291     Bad
12292     Bad
12293     Bad
Name: rating, Length: 12294, dtype: object

In [26]:
df["rating_category"] = df["rating"].apply(lambda x: "Excellent"if x>= 8 else "Good" if x >= 6 else "Average")

In [28]:
print(df[["name","rating", "rating_category"]].head(10))

                                                name  rating rating_category
0                                     Kimi no Na wa.    9.37       Excellent
1                   Fullmetal Alchemist: Brotherhood    9.26       Excellent
2                                           Gintama°    9.25       Excellent
3                                        Steins;Gate    9.17       Excellent
4                                      Gintama&#039;    9.16       Excellent
5  Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...    9.15       Excellent
6                             Hunter x Hunter (2011)    9.13       Excellent
7                               Ginga Eiyuu Densetsu    9.11       Excellent
8  Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...    9.10       Excellent
9                           Gintama&#039;: Enchousen    9.11       Excellent

In [29]:
print(df["rating_category"].value_counts())

rating_category
Good         8078
Average      3589
Excellent     627
Name: count, dtype: int64

In [30]:
# Anime basic info
anime_info = pd.DataFrame({
    "anime_id": [1, 2, 3, 4],
    "name": ["Naruto", "Bleach", "One Piece", "Death Note"]
})

# Anime ratings
anime_ratings = pd.DataFrame({
    "anime_id": [1, 2, 3, 5],  # notice: 4 is missing, 5 is extra!
    "rating": [8.5, 7.9, 8.1, 9.0]
})

In [31]:
pd.merge(anime_info, anime_ratings, on = "anime_id")

   anime_id       name  rating
0         1     Naruto     8.5
1         2     Bleach     7.9
2         3  One Piece     8.1

In [32]:
pd.merge(anime_info, anime_ratings, on = "anime_id", how = "left")

   anime_id        name  rating
0         1      Naruto     8.5
1         2      Bleach     7.9
2         3   One Piece     8.1
3         4  Death Note     NaN

In [33]:
pd.merge(anime_info, anime_ratings, on = "anime_id", how = "outer")

   anime_id        name  rating
0         1      Naruto     8.5
1         2      Bleach     7.9
2         3   One Piece     8.1
3         4  Death Note     NaN
4         5         NaN     9.0

In [34]:
my_ratings = pd.DataFrame({
    "name": ["Naruto", "Death Note", "Attack on Titan"],
    "my_rating": [9.5, 9.8, 9.2]
})

In [37]:
pd.merge(df, my_ratings, on = "name")

,anime_id,name,genre,type,episodes,rating,members,rating_category,my_rating
0,1535,Death Note,"Mystery, Police, Psychological, Supernatural, ...",TV,37,8.71,1013917,Excellent,9.8
1,20,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,7.81,683297,Good,9.5

In [38]:
df[df["name"].str.contains("Attack", case = False)]

,anime_id,name,genre,type,episodes,rating,members,rating_category
840,87,Mobile Suit Gundam: Char&#039;s Counterattack,"Drama, Mecha, Military, Sci-Fi, Space",Movie,1,7.81,19258,Good
3892,1550,Attack No.1,"Drama, Shoujo, Sports",TV,104,6.85,3676,Good
3933,4339,Ashita e Attack!,"Drama, School, Sports",TV,23,6.84,616,Good
4668,3081,Attacker You!,"Action, Romance, Shoujo, Sports",TV,58,6.66,2733,Good
4775,2306,Mobile Suit SD Gundam&#039;s Counterattack,"Comedy, Mecha, Parody",OVA,2,6.64,1982,Good
5311,9166,Attack No.1: Namida no Sekai Senshuken,"Drama, Shoujo, Sports",Movie,1,6.49,248,Good
5446,9163,Attack No.1 (1970),"Drama, Shoujo, Sports",Movie,1,6.45,329,Good
5711,9165,Attack No.1: Namida no Kaiten Receive,"Drama, Shoujo, Sports",Movie,1,6.37,248,Good
5918,9164,Attack No.1: Namida no Fushichou,"Drama, Shoujo, Sports",Movie,1,6.31,248,Good
6256,11919,Zoku Attacker You! Kin Medal e no Michi,"Romance, Sports",TV,52,6.20,340,Good
9011,32707,Jewelpet: Attack Chance!?,"Comedy, Fantasy, Magic, Shoujo",ONA,Unknown,5.89,234,Average
9516,24259,Mechano: Scientific Attack Force,"Comedy, Dementia, Fantasy, Horror, Music, Parody",OVA,3,2.55,120,Average

In [43]:
pd.pivot_table(df, values = ["rating", "members"],
               index = "type",
               aggfunc = ["mean","max","min","count"])

                 mean                max            min          count
              members    rating  members rating members rating members rating
type
Movie    10360.340716  6.318058   466254  10.00       5   1.92    2348   2297
Music     1311.840164  5.588996    71136   8.38      24   3.28     488    488
ONA       4114.030349  5.643298   144898   8.26      25   2.58     659    652
OVA       5986.139837  6.375221   305165   9.25      17   2.00    3311   3285
Special   7676.060859  6.523501   160423   8.66      24   1.67    1676   1671
TV       42683.658305  6.902299  1013917   9.60      12   2.67    3787   3671

In [44]:
df[(df["type"] == "Movie") & (df["rating"] == 10.0)][["name", "rating", "members"]]

                                          name  rating  members
10464  Taka no Tsume 8: Yoshida-kun no X-Files    10.0       13

In [45]:
pd.pivot_table(df,
               values="rating",
               index="type",
               aggfunc="mean").sort_values("rating", ascending=False)

           rating
type
TV       6.902299
Special  6.523501
OVA      6.375221
Movie    6.318058
ONA      5.643298
Music    5.588996